# .github/workflows/sitemap.yml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Génération automatique du sitemap

on:
  push:
    branches:
      - main

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4.2.2

      - name: Générer le sitemap
        uses: cicirello/generate-sitemap@v1.10.2
        with:
          base-url: https://buonomolea.github.io/portfolio-lea-buonomo
          output: sitemap.xml

      - name: Commit & push du sitemap
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "🗺️ Mise à jour automatique du sitemap"
          file_pattern: sitemap.xml
